### ISSUE TITLE
UniteSessionSave make incorrect sessions.

### ISSUE THREAD

**Issue by bootleq** [Shougo/unite-session#5]
Hi, Shougo:

I can't save session files correctly, follow steps below:
https://gist.github.com/bootleq/6339138#comment-894604
It's strange that it was fine in the past, but I can't make it work by revert to old revisions and old Vim versions.

**Comment by gaving** [comment]
Noticed this wasn't working also which is a shame because I like the session source. :disappointed: 

@Shougo out of interest, do you use anything else for managing your sessions?

**Comment by Shougo** [comment]
I don't use sessions.
But I think https://github.com/osyo-manga/vim-reanimate is better.

**Comment by gaving** [comment]
@Shougo Thanks, will check it out!
